version: '3.3'

services:
  github_runner_x:
    user: docker
    container_name: github_runner_x
    build: .
    ports:
      - '3011:3000'
    environment:
      NODE_ENV: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
