version: '3.3'

services:
  github:
    user: docker
    container_name: github_runner
    build: .
    ports:
      - '3011:3000'
    environment:
      NODE_ENV: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
